export const paths = {
  home: "/",
  product: (id) => `/product/${id}`,
  login: "/login",
  cart: (id = "") => `/cart/${id}`,
  register: "/register",
  profile: "/profile",
  shipping: "/shipping",
  payment: "/payment",
  placeOrder: "/placeorder",
  order: (id) => `/order/${id}`,
  user: (id) => `/user/${id}/edit`,
  adminUserList: "/admin/userList",
  productList: "/admin/productlist",
  productListPage: (pageNumber) => `/admin/productlist/${pageNumber}`,
  orderList: "/admin/orderlist",
  adminUserEdit: (id) => `/admin/user/${id}/edit`,
  adminProductEdit: (id) => `/admin/product/${id}/edit`,
  search: (keyword) => `/search/${keyword}`,
  page: (pageNumber) => `/page/${pageNumber}`,
  searchAndPage: (keyword, pageNumber) =>
    `/search/${keyword}/page/${pageNumber}`,
};
