export const paths = {
  home: "/",
  product: (id) => `/product/${id}`,
  login: "/login",
  cart: (id = "") => `/cart/${id}`,
  register: "/register",
  profile: "/profile",
  shipping: "/shipping",
  payment: "/payment",
  placeOrder: "/placeorder",
  order: (id) => `/order/${id}`,
  user: (id) => `/user/${id}/edit`,
  adminUserList: "/admin/userList",
  productList: "/admin/productlist",
  orderList: "/admin/orderlist",
  adminUserEdit: (id) => `/admin/user/${id}/edit`,
  adminProductEdit: (id) => `/admin/product/${id}/edit`,
};
